package com.example.agb;

import androidx.appcompat.app.AppCompatActivity;
import androidx.drawerlayout.widget.DrawerLayout;

import android.os.Bundle;
import android.view.View;
import android.view.animation.AlphaAnimation;
import android.widget.Button;
import android.widget.TextView;

public class KnowMoreActivity extends AppCompatActivity {

    private Button agb, expenses, income, work;
    private TextView reponse;

    DrawerLayout drawerLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_know_more);

        drawerLayout = findViewById(R.id.drawer_layout);

        agb = findViewById(R.id.button_agb);
        expenses = findViewById(R.id.button_expenses);
        income = findViewById(R.id.button_income);
        work = findViewById(R.id.button_work);

        reponse = findViewById(R.id.reponse);

        agb.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //animation button
                AlphaAnimation alphaagb = new AlphaAnimation(0f, 1f);
                alphaagb.setDuration(100);
                agb.startAnimation(alphaagb);
                //end animation button
                reponse.setText("AGB is more than just a mobile application, it is your personal assistant that will help you manage efficiently your budget and your daily expenses." +
                        "Thanks to the easy-to-use interfaces, AGB helps you saving money every month and tracking your spending in each category as well as the money saved with a balance sheet depending on your saving targets.");
            }
        });

        expenses.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //animation button
                AlphaAnimation alphaexp = new AlphaAnimation(0f, 1f);
                alphaexp.setDuration(100);
                expenses.startAnimation(alphaexp);
                //end animation button
                reponse.setText( "your expenses are the costs required on items and categories on which you spend your money on. On AGB, they are divided in:\n" +
                        "- Food: Contains your consumption in food including the money spent in restaurant, items bought from food-selling stores.\n " +
                        "- Studies: Includes all the education fees spent throughout the year including the school supplies.\n " +
                        "- Clothing: Money spent on items of clothes. \n" +
                        "- Home: Payment dedicated to home-related fees like rent, electricity and gas bills, water bills... and house furniture that includes home equipment and essential devices.\n " +
                        "- Transport: All your personal transportation costs (fuel cost for your car, public transport subscriptions and tickets...) \n" +
                        "- Technology: Money spent on high-tech devices and items you buy for yourself (gaming devices, phones, computers...) \n" +
                        "- Health: Includes the doctor, hospital and medical bills during the month. \n" +
                        "- Groceries: This category encompasses your money spent at the stores, you just need to add the final amount found on the bill at the grocery stores and supermarkets.. \n" +
                        "- Entertainment: These expenses include the cost of entertaining yourself at social and sports events, movie and theater tickets, among other things like memberships in sport clubs. \n" +
                        "- Other: Includes all the money spent on other categories than those mentionned below such as reparation costs.\n");
            }
        });

        income.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //animation button
                AlphaAnimation alphainco = new AlphaAnimation(0f, 1f);
                alphainco.setDuration(100);
                income.startAnimation(alphainco);
                //end animation button
                reponse.setText("- Business: represents the amount of money you get through the sales you made for a month.\n" +
                        "- Real Estate : cash generated by buying and selling or renting properties.\n" +
                        "- Salary:  the money you get monthly thanks to your job.\n" +
                        "- Other: Includes all other types of incomes that haven't been mentionned such as loans, borrowings, heritage...");
            }
        });

        work.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //animation button
                AlphaAnimation alphawork = new AlphaAnimation(0f, 1f);
                alphawork.setDuration(100);
                work.startAnimation(alphawork);
                //end animation button
                reponse.setText("The concept is pretty simple. You only have to create your account using your mail and then add your personal informations including your sources taht you will update" +
                        "every time you get money in on of those categories or more and the amount of money that you aim to save each month. You will then update your expenses eaxh time you spend money on one of the categories of expenses cited" +
                        "on the interface.\n You will then be able to follow in real time the evolution of the amount of money that you still have and how are your expenses divided through the" +
                        "various categories.");
            }
        });

    }

    // onClick Methods

    //Click Menu
    public void ClickMenu(View view){
        //animation button
        AlphaAnimation alphaOpenMenu = new AlphaAnimation(0f, 1f);
        alphaOpenMenu.setDuration(100);
        findViewById(R.id.MenuClickable).startAnimation(alphaOpenMenu);
        //end animation button
        MyExpenses.openDrawer(drawerLayout);
    }

    //Click Logo
    public void ClickLogo(View view){
        //animation button
        AlphaAnimation alphaCloseLogo = new AlphaAnimation(0f, 1f);
        alphaCloseLogo.setDuration(100);
        findViewById(R.id.imageView17).startAnimation(alphaCloseLogo);
        //end animation button
        MyExpenses.closeDrawer(drawerLayout);
    }

    // Click Home
    public void ClickHome(View view){
        //animation button
        AlphaAnimation alphaOpenStat = new AlphaAnimation(0f, 1f);
        alphaOpenStat.setDuration(100);
        findViewById(R.id.StatisticsClickable).startAnimation(alphaOpenStat);
        //end animation button
        MyExpenses.redirectActivity(this,statistics.class);
    }

    //Click Profile
    public void ClickProfile(View view){
        //animation button
        AlphaAnimation alphaOpenProfile = new AlphaAnimation(0f, 1f);
        alphaOpenProfile.setDuration(100);
        findViewById(R.id.ProfileClickable).startAnimation(alphaOpenProfile);
        //end animation button
        MyExpenses.redirectActivity(this,ProfileActivity.class);
    }

    //Click Incomes
    public void ClickIncomes(View view){
        //animation button
        AlphaAnimation alphaOpenInco = new AlphaAnimation(0f, 1f);
        alphaOpenInco.setDuration(100);
        findViewById(R.id.IncomesClickable).startAnimation(alphaOpenInco);
        //end animation button
        MyExpenses.redirectActivity(this,IncomesActivity.class);
    }


    // Click Dashboard
    public void ClickDashboard(View view){
        //animation button
        AlphaAnimation alphaOpenDash = new AlphaAnimation(0f, 1f);
        alphaOpenDash.setDuration(100);
        findViewById(R.id.DashboardClickable).startAnimation(alphaOpenDash);
        //end animation button
        MyExpenses.redirectActivity(this,HomeActivity.class);
    }

    //Click Expenses
    public void ClickExpenses(View view){
        //animation button
        AlphaAnimation alphaOpenExpen = new AlphaAnimation(0f, 1f);
        alphaOpenExpen.setDuration(100);
        findViewById(R.id.ExpensesClickable).startAnimation(alphaOpenExpen);
        //end animation button
        MyExpenses.redirectActivity(this,MyExpenses.class);
    }

    //Click Know More
    public void ClickKnowMore(View view){
        //animation button
        AlphaAnimation alphaOpenKnow = new AlphaAnimation(0f, 1f);
        alphaOpenKnow.setDuration(100);
        findViewById(R.id.KnowMoreClickable).startAnimation(alphaOpenKnow);
        //end animation button
        MyExpenses.redirectActivity(this,KnowMoreActivity.class);
    }

    //Click About Us
    public void ClickAboutUs(View view){
        //animation button
        AlphaAnimation alphaOpenAbout = new AlphaAnimation(0f, 1f);
        alphaOpenAbout.setDuration(100);
        findViewById(R.id.AboutUsClickable).startAnimation(alphaOpenAbout);
        //end animation button
        MyExpenses.redirectActivity(this,AboutUs.class);
    }

    //Click Log Out
    public void ClickLogout(View view){
        //animation button
        AlphaAnimation alphaOpenLogOut = new AlphaAnimation(0f, 1f);
        alphaOpenLogOut.setDuration(100);
        findViewById(R.id.LogOutClickable).startAnimation(alphaOpenLogOut);
        //end animation button
        MyExpenses.Logout(this);
    }

    //Method onPause
    @Override
    protected void onPause(){
        super.onPause();
        MyExpenses.closeDrawer(drawerLayout);
    }
}